sudo: required 
services: 
  - docker 

before_install: 
  - docker build -t j4ven/react-test -f ./client/Dockerfile.dev ./client

script: 
 - docker run -e CI=true j4ven/react-test npm test

after_success:
 - docker build -t j4ven/multi-client ./client 
 - docker build -t j4ven/multi-nginx ./nginx 
 - docker build -t j4ven/multi-server ./server
 - docker build -t j4ven/multi-worker ./worker
 # Log in to the docker CLI 
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 # Push images to docker hub
 - docker push j4ven/multi-client 
 - docker push j4ven/multi-nginx
 - docker push j4ven/multi-server
 - docker push j4ven/multi-worker